export enum SignalType {
  RSI_OVERBOUGHT = "RSI_OVERBOUGHT",
  RSI_OVERSOLD = "RSI_OVERSOLD",
  VOLUME_SPIKE = "VOLUME_SPIKE",
  VOLUME_DECLINE = "VOLUME_DECLINE",
  REJECTION_WICK = "REJECTION_WICK",
  PRICE_LEVEL_BREAK = "PRICE_LEVEL_BREAK",
  MACD_DIVERGENCE = "MACD_DIVERGENCE",
  TREND_ALIGNMENT = "TREND_ALIGNMENT",
  PRICE_IN_ENTRY_ZONE = "PRICE_IN_ENTRY_ZONE",
}

export enum SignalRole {
  PRECONDITION = "PRECONDITION",
  TRIGGER = "TRIGGER",
}

