export enum SetupType {
  RESISTANCE_REJECTION = "RESISTANCE_REJECTION",
  SUPPORT_BREAKDOWN = "SUPPORT_BREAKDOWN",
  RETEST_SHORT = "RETEST_SHORT",
  TREND_CONTINUATION = "TREND_CONTINUATION",
  MEAN_REVERSION = "MEAN_REVERSION",
}

export enum SetupState {
  FORMING = "FORMING",
  ACTIVE = "ACTIVE",
  TRIGGERED = "TRIGGERED",
  EXPIRED = "EXPIRED",
  INVALIDATED = "INVALIDATED",
}

export enum SetupDirection {
  LONG = "LONG",
  SHORT = "SHORT",
}

